### ISSUE TITLE
Invalid interpolation for SMTP password because of special characters

### ISSUE THREAD

**Issue by DracoMilesX** [service-bot/servicebot-deploy#1]
Tried to run the docker file but the password I use for my SMTP account has special characters in it when I try to run docker-compose build I get:

"ERROR: Invalid interpolation format for "environment" option in service "servicebot": "p@ssword" "

When removing the special character it works fine

**Comment by bsears90** [comment]
This appears to be a docker issue, escaping the character or switching to single quotes from double quotes appears to be solutions, in the future we are considering changing it from a raw docker-compose to a script which generates a docker-compose which would allow us to make sure the characters are properly escaped.

**Comment by darafsheh** [comment]
Thanks @bsears90 
@DracoMilesX Let us know if you need any other help and thank you for letting us know about this bug :)

**Comment by DracoMilesX** [comment]
Thanks @bsears90 and @darafsheh.

Tried it but still had same issue apparently it is because the special character is $ as last as well so I needed to add an extra $ to escape character and now it is working.

**Comment by bsears90** [comment]
Thanks @DracoMilesX, I added a line in the readme about escaping the $ with a link to the docker-compose documentation.
